---

language: minimal

git:
  depth: 10

env:
  global:
    - PROG_VER=$(head -n 1 VERSION.txt)

deploy_build: &deploy
  - provider: releases
    api_key:
      secure: "0671vAjL2m6gqjDSdkdjiyfDwuR8uLYrE6OCaeaX9iLvqSxmKAffkLlCZXU9fevmTglEMSmarcmHtwy1AYcqBClChl0dup2YvmM+BzsTfDSjZT43asI1Ok7MJALqqCa/xPO15HH1XfvstHeuOCM16nB61VQKT1+an0T9oz96PNIr5oS/Q8owmaWHvbB18IBoeTNvUZl0OvaqjNGZJ9JnBvBTROPDvsfud1DxlPmlTaCxh+yx8yAZYX2nLOkJFlWhG4b7mtcrlitVENcdjJ90qY4c01uzH3cYNdVn4PH/z0s+cAQT36f2zSX8UpsfBxbsBpB6ANS9Ig4gPp8eOtuhfpd2lOH6fL/DwAaxh9FGbTH5n9eR4cO9bEkmW5BoUeDpcIboIVZKrtZI97/MiRtwMfQzleQuwWuDpanaMqiY+LdS6vllG4kQjGck9fWj5wbaHR/MDTlAODc5/WUYA+69MDjPK/JI34/rPIag+8ZF2pF2VLyVC1kbvpngsYkcvQTRRSWrb6Cj0i7ggrBrCOmU2RrfkiKUGarukaCel/9U2dxnmkxPpfKBVXD0v6ylcUEofMJ6ml4lcGH8XX1jTNlUQebu7uhbfyhsJA9IEyMKXX3RHaq7Tf1XyCtZYIo2sAkFG103u/zSbkVZOAa8qoWqwFO8gx5MAa7ZRJVbuBNswBk="
    file: $artifact
    skip_cleanup: true
    on:
      tags: true

linux_after_success: &linux_after_success
  - md5sum $artifact
  - shasum -a 1 $artifact
  - shasum -a 256 $artifact
  - if [ -n "$TRAVIS_TAG" ] ; then
      curl -F "file=@$artifact" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ;
      curl -F "file=@./transgui" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ;
    else
      setup/upload_asset.sh $artifact ;
    fi

stages:
  - static test
  - build

env_template:
  - &linux_env
    os: linux
    dist: bionic
    services:
      - docker

  - &linux_build_env
    <<: *linux_env
    stage: build

  - &nodejs_static_test_env
    <<: *linux_env
    stage: static test
    language: node_js
    node_js: 16
    install:
      - npm i -g $task
    before_script:
      - type $task

matrix:
  include:
    - os: windows
      language: shell
      stage: build
      env:
        - arch=win32
        - artifact1=./Release/transgui-$PROG_VER-setup.exe
        - artifact2=./Release/transgui-$PROG_VER-i386-win32.zip
      before_install:
        - echo $PATH
        - compgen -c | sort | uniq
        - cd setup/win && sed -i "s/pause//g" *
      install:
        - sh -c 'cd setup/win && ./install_deps.bat'
      script:
        - sh -c 'cd setup/win && ./make_setup.bat'
        - sh -c 'cd setup/win && ./make_zipdist.bat'
      after_success:
        - md5 $artifact1 $artifact2
        - shasum -a 1 $artifact1 $artifact2
        - shasum -a 256 $artifact1 $artifact2
        - if [ -n "$TRAVIS_TAG" ] ; then
            curl -F "file=@$artifact1" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ;
            curl -F "file=@$artifact2" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ;
            curl -F "file=@./transgui" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ;
          else
            setup/upload_asset.sh $artifact1 ;
            setup/upload_asset.sh $artifact2 ;
          fi
      deploy: *deploy

notifications:
  email:
    on_failure: true
